# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

# This file is maintained in https://github.com/WeblateOrg/meta/
# Configuration for https://kodiakhq.com/
version = 1

[merge]
method = "rebase"

[update]
ignored_usernames = ["weblate", "pre-commit-ci", "deepsource-autofix", "rennovate"]
