# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

test_patterns = [
  "**/test_*.py"
]
version = 1

[[analyzers]]
enabled = true
name = "python"

[[analyzers]]
name = "test-coverage"

[analyzers.meta]
runtime_version = "3.x.x"
