---
kind: pipeline
name: python-2

steps:
- name: test
  image: python:2
  commands:
  - pip install -U -r requirements-test.txt -r requirements-ci.txt
  - py.test --cov=translation_finder translation_finder README.rst
  - ./setup.py sdist
  - twine check dist/*
  - flake8

---
kind: pipeline
name: python-3-5

steps:
- name: test
  image: python:3.5
  commands: 
  - pip install -U -r requirements-test.txt -r requirements-ci.txt
  - py.test --cov=translation_finder translation_finder README.rst
  - ./setup.py sdist
  - twine check dist/*
  - flake8

---
kind: pipeline
name: python-3-7

steps:
- name: test
  image: python:3.7
  commands: 
  - pip install -U -r requirements-test.txt -r requirements-ci.txt
  - py.test --cov=translation_finder translation_finder README.rst
  - ./setup.py sdist
  - twine check dist/*
  - flake8
...

