# This file is maintained in https://github.com/WeblateOrg/meta/
name: Issue labeled

on:
  issues:
    types: [labeled]

jobs:
  issueLabeled:
    runs-on: ubuntu-latest
    steps:
      - name: Add backlog comment
        uses: peter-evans/create-or-update-comment@v1
        if: github.event.label.name == 'backlog'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue has been added to backlog. It is not scheduled on our road map, but it might be eventually implemented. In case you desperately need this feature, please consider helping or [funding the development](https://weblate.org/support/).
      - name: Add undecided comment
        uses: peter-evans/create-or-update-comment@v1
        if: github.event.label.name == 'undecided'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue has been put aside. Currently, it is unclear whether it will be ever implemented as it seems to cover too narrow use case or doesn't seem to fit into Weblate. Please try to clarify the use case or consider proposing something more generic to make it useful to more users.
