name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -U -r requirements-test.txt -r requirements-ci.txt
    - name: Lint with flake8
      run: |
        flake8
    - name: Test with pytest
      run: |
        py.test --cov=translation_finder translation_finder README.rst
        coverage xml
    - uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        name: Python ${{ matrix.python-version }}
    - name: Check sdist
      run: |
        python ./setup.py sdist
        twine check dist/*
